{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plogr
  version: {{ version|replace("-", "_") }}

source:
  fn: plogr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/plogr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plogr/plogr_{{ version }}.tar.gz
  sha256: 0e63ba2e1f624005fe25c67cdd403636a912e063d682eca07f2f1d65e9870d29

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('plogr')"           # [not win]
    - "\"%R%\" -e \"library('plogr')\""  # [win]

about:
  home: https://github.com/krlmlr/plogr#readme
  license: MIT
  summary: ' A simple header-only logging library for C++. Add ''LinkingTo: plogr'' to ''DESCRIPTION'',
    and ''#include <plogr.h>'' in your C++ modules to use it.'
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
