appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hx5WNDhDe89EN81g8baNWtaf05C706rE2IOL4RZIUmCvjStMDjH6RjJylooeBFyy4ptqZy2gbcMpy9QBxJpf+5wjXZklzgw6KGMaXk6XCqirbIm0PoCCBIzSRLMU/9xDSiCqeSlVB1kbz8CSbPPt5qEjf/EpGj8LaddjYLCk6WujZ0N2B2JC4WmFvAGOpfbB3z9KwfUBDnANaEnxP8olK1QkkC8UuwU/LpdCoM96QXMtM+unIAjr3nKy+gQsPEA0IHUhqnvXxj1cA4qQMFx4iGZBl3c3SX8sSM6RIi31Wx0G4cI8mLjwPO0iSfQvMLk3taFqr4ENY18VNUbli95tu879MwTrEECBYGxiAXaeilcMIV4ufh18FYlFfEneZHNeHBRTuMFgJKGaL4iqrApz7aqe31/Z/AYYDFmhT8imwZ6rPnuTCgCuqJG4926pQINiYJZaVrU5aejDaJrStJWU8+Sz9sYSi8TL1dgV2laLaZeQSRi93lDpkmlffHUhuo2xRuyJfG3ON+WqsB9VjU/8MCwdmAf/btUrDaplO62NFM3dUq1EoJ0MfwDbAxxXa7dj+v8UWSClB9QnRRuAccT4VtiDghujg53YAAAMbW3Fo40T4FRUhNGpgiH9tJrq+gKSCP4hfj5R63D+tcx8eit4FB+UhRmpel60Wfapxo2LxNc=
